In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/content/Salary_Data.csv")

In [3]:
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
data.isnull().any()

YearsExperience    False
Salary             False
dtype: bool

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [6]:
x = data.iloc[:,0:1].values
y = data.iloc[:,1].values

In [7]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [8]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 1000)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
sal = Sequential()

In [13]:
sal.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [14]:
sal.add(Dense(2,kernel_initializer="random_uniform",activation="relu"))

In [15]:
sal.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [16]:
sal.compile("adam","mean_squared_error",metrics = ["MSE"])

In [17]:
sal.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 548ms/step - loss: 6277245440.0000 - MSE: 6277245440.0000
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 6277245440.0000 - MSE: 6277245440.0000
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 6277245440.0000 - MSE: 6277245440.0000
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 6277245440.0000 - MSE: 6277245440.0000
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 6277244416.0000 - MSE: 6277244416.0000
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 6277244416.0000 - MSE: 6277244416.0000
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 6277244416.0000 - MSE: 6277244416.0000
Epoch 8/100
1/1 [==============================] - 0s 8ms/step - loss: 6277244416.0000 - MSE: 6277244416.0000
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 6277244416.0000 - MSE: 6277244416.0000
Epoch 10

In [18]:
ypred = sal.predict(x_test)
ypred

array([[0.1406427 ],
       [0.14030547],
       [0.16093904],
       [0.14030547],
       [0.15488043],
       [0.15790974]], dtype=float32)

In [19]:
y_test

array([109431., 105582.,  43525., 112635.,  55794.,  60150.])

In [20]:
sal.predict(sc.transform([[1.1]]))

array([[0.1636654]], dtype=float32)

In [21]:
sal.predict_classes(sc.transform([[1.1]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]], dtype=int32)

In [22]:
sal.predict(sc.transform([[10.5]]))

array([[0.14030547]], dtype=float32)

In [23]:
sal.predict_classes(sc.transform([[10.5]]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]], dtype=int32)